"""Parse the EDGAR samples through Docling, warming the cache the tests use.

    uv run python scripts/parse_samples.py                 # every fetched sample
    uv run python scripts/parse_samples.py --only verizon_2025
    uv run python scripts/parse_samples.py --drafts        # also write draft gold files

Prints, per sample: pages, seconds, seconds per page, peak memory, and the
waterfalls found. Docling runs on CPU and needs ~1-1.5 GB; stop Docker and
vLLM first on a 16 GB machine.

``--drafts`` writes ``data/gold/parsing/<id>.json`` with ``"reviewed": false``
for any sample that has no gold file yet. A draft records what the parser
found; it only becomes gold once a person has checked it against the PDF and
set ``reviewed`` to true.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from typing import Any

from secai.config import REPO_ROOT, get_settings
from secai.parsing.cache import load_or_parse
from secai.parsing.pipeline import analyse

SAMPLES = REPO_ROOT / "data" / "samples"
CACHE = SAMPLES / ".cache"
GOLD = REPO_ROOT / "data" / "gold" / "parsing"
STEP_PREFIX_CHARS = 60


def peak_memory_gb() -> float | None:
    try:
        import psutil
    except ImportError:  # pragma: no cover - docling depends on psutil
        return None
    info = psutil.Process().memory_info()
    peak = getattr(info, "peak_wset", None) or getattr(info, "rss", 0)
    return float(peak) / 1e9


def draft_gold(
    sample: dict[str, Any], page_count: int, sections: set[str], waterfalls: list[Any]
) -> dict[str, Any]:
    return {
        "id": sample["id"],
        "reviewed": False,
        "review_notes": "Draft generated by scripts/parse_samples.py. Check every step against "
        "the PDF, delete waterfalls that are not payment priorities, then set reviewed=true.",
        "page_count": page_count,
        "sections": sorted(sections),
        "waterfalls": [
            {
                "title_contains": w.title[:80],
                "start_page": w.start_page,
                "steps": [step.text[:STEP_PREFIX_CHARS] for step in w.steps],
            }
            for w in waterfalls
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--only", nargs="*", help="sample ids (default: all fetched)")
    parser.add_argument("--drafts", action="store_true", help="write draft gold files")
    args = parser.parse_args()

    manifest = json.loads((SAMPLES / "manifest.json").read_text(encoding="utf-8"))
    settings = get_settings().parsing
    rows: list[str] = []

    for sample in manifest["samples"]:
        sample_id = sample["id"]
        if args.only and sample_id not in args.only:
            continue
        pdf = SAMPLES / f"{sample_id}.pdf"
        if not pdf.is_file():
            print(f"[{sample_id}] not fetched; run scripts/fetch_samples.py", file=sys.stderr)
            continue

        started = time.perf_counter()
        result, from_cache = load_or_parse(pdf, settings, CACHE)
        seconds = time.perf_counter() - started
        _, sections, waterfalls = analyse(result)
        canonical = {s.canonical for s in sections if s.canonical}

        source = (
            "cache" if from_cache else f"{seconds:.0f}s ({seconds / result.page_count:.1f} s/page)"
        )
        peak = peak_memory_gb()
        peak_text = f"peak {peak:.2f} GB" if peak is not None else "peak n/a"
        print(
            f"\n[{sample_id}] {result.page_count} pages, {len(result.blocks)} blocks, "
            f"{len(result.tables)} tables ({result.fallback_tables} fallback attempts), "
            f"{source}, {peak_text}"
        )
        print(f"  sections: {sorted(canonical)}")
        for w in waterfalls:
            print(f"  waterfall p{w.start_page}-{w.end_page} [{len(w.steps)} steps] {w.title[:90]}")
        rows.append(f"| {sample_id} | {result.page_count} | {source} | {len(waterfalls)} |")

        gold = GOLD / f"{sample_id}.json"
        if args.drafts and not gold.is_file():
            GOLD.mkdir(parents=True, exist_ok=True)
            gold.write_text(
                json.dumps(draft_gold(sample, result.page_count, canonical, waterfalls), indent=2)
                + "\n",
                encoding="utf-8",
            )
            print(f"  draft gold written: {gold.relative_to(REPO_ROOT)}")
        sys.stdout.flush()

    print("\n| Sample | Pages | Parse time | Waterfalls |\n|---|---|---|---|")
    print("\n".join(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
